// Catálogo Russo Store — Linha Mizuno Wave Prophecy COMPLETA (75 modelos)
// Todos os produtos R$ 399,90 | Tamanhos 37 ao 45
// Imagens baixadas do site oficial Mizuno (https://www.mizuno.com.br/linha-wave-prophecy)

export type Product = {
  id: string;
  name: string;
  category: "Mizuno Wave Prophecy";
  variant: string;
  price: number;
  image: string;
  description: string;
  highlight?: string;
  badge?: string;
  colors?: string[];
};

export const WHATSAPP_NUMBER = "5516992800385";
export const STORE_NAME = "Russo Store";

// Tamanhos brasileiros disponíveis para todos os modelos
export const SIZES = [37, 38, 39, 40, 41, 42, 43, 44, 45] as const;

// Filtros rápidos por variante
export const CATEGORIES = [
  {
    id: "Todos",
    name: "Todos",
    description: "Coleção completa (75 modelos)",
    icon: "Footprints",
  },
  {
    id: "M",
    name: "Prophecy M",
    description: "Modelo principal Infinity Wave",
    icon: "Zap",
  },
  {
    id: "LS",
    name: "Prophecy LS",
    description: "Lifestyle urbano e casual",
    icon: "Sparkles",
  },
  {
    id: "Beta",
    name: "Beta",
    description: "Linha Beta — design arrojado",
    icon: "Hexagon",
  },
  {
    id: "MOC",
    name: "MOC",
    description: "Moc-toe premium",
    icon: "Crown",
  },
  {
    id: "Prophecy 13",
    name: "Prophecy 13",
    description: "Geração 13 clássica",
    icon: "Star",
  },
  {
    id: "Prophecy 14",
    name: "Prophecy 14",
    description: "Geração 14 atualizada",
    icon: "TrendingUp",
  },
  {
    id: "Collab",
    name: "Collabs",
    description: "Edições de colaboração",
    icon: "Award",
  },
  {
    id: "GTX",
    name: "GTX",
    description: "Gore-Tex impermeável",
    icon: "Droplets",
  },
] as const;

export const PRODUCTS: Product[] = [
  {
    id: "mzp-001",
    name: "Kit 1 Tênis Masculino Mizuno Wave Prophecy 13 e 3 Pares de Meia Cano Médio",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/kit-1-tenis-masculino-mizuno-wave-prophecy-13-e-3-pares-de-meia-cano-medio-10218.jpg",
    description: `Kit 1 Tênis Masculino Mizuno Wave Prophecy 13 e 3 Pares de Meia Cano Médio. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-002",
    name: "Kit 1 Tênis Masculino Mizuno Wave Prophecy 13 e 3 Pares de Meia Cano Médio",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/kit-1-tenis-masculino-mizuno-wave-prophecy-13-e-3-pares-de-meia-cano-medio-10218.jpg",
    description: `Tenha máxima tração com borracha X10 e cabedal em monofilamento. Aproveite frete grátis* e parcelas de 10x s/ juros. Compre o seu agora!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-003",
    name: "Kit 1 Tênis Masculino Mizuno Wave Prophecy 13 e 3 Pares de Meia Cano Médio",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/kit-1-tenis-masculino-mizuno-wave-prophecy-13-e-3-pares-de-meia-cano-medio-10218.jpg",
    description: `Kit 1 Tênis Masculino Mizuno Wave Prophecy 13 e 3 Pares de Meia Cano Médio. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-004",
    name: "Kit 1 Tênis Masculino Mizuno Wave Prophecy 14 e 3 Pares de Meia Cano Médio Basic Tam. 39-44",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/kit-1-tenis-masculino-mizuno-wave-prophecy-14-e-3-pares-de-meia-cano-medio-basic.jpg",
    description: `A entressola possui a tecnologia Infinity Wave em toda a sua extensão dando a ele um visual moderno e tecnológico. O cabedal, com referência ao estilo esportivo moderno, conta com monofilamento que garante um design inovador, proporcionando um melhor ajuste aos seus pés. Além disso, seu solado tem a tecnologia X10, um composto de borracha com carbono que garante maior durabilidade. As meias Mizuno são confeccionadas com matéria-prima selecionada para entregar a mais alta qualidade ao produto, sã`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-005",
    name: "Kit 1 Tênis Masculino Mizuno Wave Prophecy 14 e 3 Pares de Meia Cano Médio Basic Tam. 39-44",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/kit-1-tenis-masculino-mizuno-wave-prophecy-14-e-3-pares-de-meia-cano-medio-basic.jpg",
    description: `A entressola possui a tecnologia Infinity Wave em toda a sua extensão dando a ele um visual moderno e tecnológico. O cabedal, com referência ao estilo esportivo moderno, conta com monofilamento que garante um design inovador, proporcionando um melhor ajuste aos seus pés. Além disso, seu solado tem a tecnologia X10, um composto de borracha com carbono que garante maior durabilidade. As meias Mizuno são confeccionadas com matéria-prima selecionada para entregar a mais alta qualidade ao produto, sã`,
    badge: "Geração 14",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-006",
    name: "Kit 1 Tênis Mizuno Wave Prophecy 14 Masculino e 3 Pares de Meia Cano Médio Basic Tam. 39-44",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/kit-1-tenis-mizuno-wave-prophecy-14-masculino-e-3-pares-de-meia-cano-medio-basic.jpg",
    description: `A entressola possui a tecnologia Infinity Wave em toda a sua extensão dando a ele um visual moderno e tecnológico. O cabedal, com referência ao estilo esportivo moderno, conta com monofilamento que garante um design inovador, proporcionando um melhor ajuste aos seus pés. Além disso, seu solado tem a tecnologia X10, um composto de borracha com carbono que garante maior durabilidade. As meias Mizuno são confeccionadas com matéria-prima selecionada para entregar a mais alta qualidade ao produto, sã`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-007",
    name: "Tênis Casual Mizuno Wave Prophecy 13.2",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-13-2-102393003-004.jpg",
    description: `Sinta o aprimoramento constante de um tênis autêntico e moderno. Na loja tem frete grátis* e até 10x s/ juros. Garanta seu Prophecy hoje!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-008",
    name: "Tênis Casual Mizuno Wave Prophecy 13.2",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-13-2-102393003-030.jpg",
    description: `Sinta o aprimoramento constante de um tênis autêntico e moderno. Na loja tem frete grátis* e até 10x s/ juros. Garanta seu Prophecy hoje!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-009",
    name: "Tênis Casual Mizuno Wave Prophecy 13.2",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-13-2-102397003-012.jpg",
    description: `Sinta o aprimoramento constante de um tênis autêntico e moderno. Na loja tem frete grátis* e até 10x s/ juros. Garanta seu Prophecy hoje!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-010",
    name: "Tênis Casual Mizuno Wave Prophecy 13.2",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-13-2-102397003-014.jpg",
    description: `Sinta o aprimoramento constante de um tênis autêntico e moderno. Na loja tem frete grátis* e até 10x s/ juros. Garanta seu Prophecy hoje!`,
    badge: "Geração 13",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-011",
    name: "Tênis Casual Mizuno Wave Prophecy Beta 2 Fashion Lover",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-beta-2-fashion-lover-102208003-3-204.jpg",
    description: `Adote o visual ousado e tecnológico da entressola Infinity Wave. Aproveite frete grátis* e até 10x s/ juros na loja. Garanta o seu par já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-012",
    name: "Tênis Casual Mizuno Wave Prophecy LS Suede",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-ls-suede-unissex-cinza-8215.jpg",
    description: `Tênis Casual Mizuno Wave Prophecy LS Suede. Linha Lifestyle — conforto premium para uso urbano e casual. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Cinza"],
  },
  {
    id: "mzp-013",
    name: "Tênis Casual Mizuno Wave Prophecy LS Suede",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-ls-suede-unissex-marrom-8216.jpg",
    description: `Tênis Casual Mizuno Wave Prophecy LS Suede. Linha Lifestyle — conforto premium para uso urbano e casual. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Marrom"],
  },
  {
    id: "mzp-014",
    name: "Tênis Casual Unissex Mizuno Wave Prophecy Beta",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-casual-unissex-mizuno-wave-prophecy-beta-102015003-3-054.jpg",
    description: `Tênis Casual Unissex Mizuno Wave Prophecy Beta. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-015",
    name: "Tênis Feminino Mizuno Wave Prophecy 13",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-feminino-mizuno-wave-prophecy-13-102184002-2-262.jpg",
    description: `Tênis Feminino Mizuno Wave Prophecy 13. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-016",
    name: "Tênis Mizuno Wave Prophecy 13.2 Gradation",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-mizuno-prophecy-13-2-gradation-unissex-cinza-claro-11325.jpg",
    description: `Tênis Mizuno Wave Prophecy 13.2 Gradation. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    colors: ["Cinza"],
  },
  {
    id: "mzp-017",
    name: "Tênis Mizuno Prophecy LS x Hiroshi Nagai",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-prophecy-ls-x-hiroshi-nagai-102197003-3-090.jpg",
    description: `Tênis Mizuno Prophecy LS x Hiroshi Nagai. Linha Lifestyle — conforto premium para uso urbano e casual. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-018",
    name: "Tênis Mizuno Wave Prophecy 13",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-13-102183001-3-036.jpg",
    description: `Corra com a estabilidade máxima da placa Infinity Wave. Na nossa loja tem frete grátis* e em 10x s/ juros. Garanta o seu lançamento já!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-019",
    name: "Tênis Mizuno Wave Prophecy 13.2 Vrunk",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-13-2-vrunk-102403003-030.jpg",
    description: `Vista a collab exclusiva Mizuno + VRUNK com estilo urbano único. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-020",
    name: "Tênis Mizuno Wave Prophecy 13-S",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-13-s-102185001-1-014.jpg",
    description: `Tênis Mizuno Wave Prophecy 13-S. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-021",
    name: "Tênis Mizuno Wave Prophecy 14",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-102289003-3-033.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-022",
    name: "Tênis Mizuno Wave Prophecy 14",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-102289003-3-926.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-023",
    name: "Tênis Mizuno Wave Prophecy 14",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-102322003-3-053.jpg",
    description: `Tênis Mizuno Wave Prophecy 14. Geração 14 com atualizações de cabedal e entressola. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-024",
    name: "Tênis Mizuno Wave Prophecy 14-S",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-s-102290003-3-243.jpg",
    description: `Tênis Mizuno Wave Prophecy 14-S. Geração 14 com atualizações de cabedal e entressola. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-025",
    name: "Tênis Mizuno Wave Prophecy 14-S",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-s-masculino-azul-8434.jpg",
    description: `Tênis Mizuno Wave Prophecy 14-S. Geração 14 com atualizações de cabedal e entressola. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 14",
    highlight: "Original Mizuno",
    colors: ["Azul"],
  },
  {
    id: "mzp-026",
    name: "Tênis Mizuno Wave Prophecy 14-S",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-s-unissex-preto-8437.jpg",
    description: `Tênis Mizuno Wave Prophecy 14-S. Geração 14 com atualizações de cabedal e entressola. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 14",
    colors: ["Preto"],
  },
  {
    id: "mzp-027",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102364003-012.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-028",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102364003-030.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-029",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102364003-033.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-030",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102365001-004.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-031",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102365001-012.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-032",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102365001-030.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-033",
    name: "Tênis Mizuno Wave Prophecy 15 SE",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-se-102389003-012.jpg",
    description: `Sinta o conforto Enerzy NXT com caixa especial de 15 anos da linha. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-034",
    name: "Tênis Mizuno Wave Prophecy 15 SE",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-se-102389003-030.jpg",
    description: `Sinta o conforto Enerzy NXT com caixa especial de 15 anos da linha. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-035",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-1-345.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-036",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-1-440.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-037",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-3-059.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-038",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-3-540.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-039",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-3-639.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-040",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-unissex-azul-6368.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    highlight: "Original Mizuno",
    colors: ["Azul"],
  },
  {
    id: "mzp-041",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-unissex-cinza-7899.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Cinza"],
  },
  {
    id: "mzp-042",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-unissex-cinza-7905.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Cinza"],
  },
  {
    id: "mzp-043",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-unissex-marrom-6994.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Marrom"],
  },
  {
    id: "mzp-044",
    name: "Tênis Mizuno Wave Prophecy Beta 2 x Graphpaper",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-x-graphpaper-unissex-azul-7440.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2 x Graphpaper. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Azul"],
  },
  {
    id: "mzp-045",
    name: "Tênis Mizuno Wave Prophecy LS  x Randomevent",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls--x-randomevent-102072001-1-030.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-046",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-004.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-047",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-012.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-048",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-015.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-049",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-016.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-050",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-566.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-051",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-938.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-052",
    name: "Tênis Mizuno Wave Prophecy Ls Graphpaper",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-graphpaper-102230003-3-058.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Graphpaper. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-053",
    name: "Tênis Mizuno Wave Prophecy Ls Graphpaper",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-graphpaper-102261003-3-014.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Graphpaper. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-054",
    name: "Tênis Mizuno Wave Prophecy LS GTX",
    category: "Mizuno Wave Prophecy",
    variant: "GTX",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-gtx-102342003-030.jpg",
    description: `Tênis Mizuno Wave Prophecy LS GTX. Tecnologia Gore-Tex impermeável para qualquer condição climática. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "GTX",
    colors: ["Variada"],
  },
  {
    id: "mzp-055",
    name: "Tênis Mizuno Wave Prophecy LS Midnight Velocity",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-midnight-velocity-102392003-004.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Midnight Velocity. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-056",
    name: "Tênis Mizuno Wave Prophecy LS Midnight Velocity",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-midnight-velocity-102392003-030.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Midnight Velocity. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-057",
    name: "Tênis Mizuno Wave Prophecy LS Millennium",
    category: "Mizuno Wave Prophecy",
    variant: "Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-millennium-102310003-3-030.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Millennium. Edição especial com acabamento premium e detalhes únicos. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Edição Especial",
    colors: ["Variada"],
  },
  {
    id: "mzp-058",
    name: "Tênis Mizuno Wave Prophecy LS Mimetics",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-mimetics-unissex-cinza-8188.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Mimetics. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Cinza"],
  },
  {
    id: "mzp-059",
    name: "Tênis Mizuno Wave Prophecy LS Neon",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-neon-unissex-marrom-11323.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Neon. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Marrom"],
  },
  {
    id: "mzp-060",
    name: "Tênis Mizuno Wave Prophecy LS Nomad",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-nomad-unissex-bege-6395.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Nomad. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Edição Especial",
    highlight: "Original Mizuno",
    colors: ["Bege"],
  },
  {
    id: "mzp-061",
    name: "Tênis Mizuno Wave Prophecy Ls Shinzo",
    category: "Mizuno Wave Prophecy",
    variant: "Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-shinzo-102262003-3-941.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Shinzo. Edição especial com acabamento premium e detalhes únicos. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Edição Especial",
    colors: ["Variada"],
  },
  {
    id: "mzp-062",
    name: "Tênis Mizuno Wave Prophecy Ls Sport",
    category: "Mizuno Wave Prophecy",
    variant: "LS Sport",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-sport-102300003-3-362.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Sport. Versão esportiva da linha LS para performance e lifestyle. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-063",
    name: "Tênis Mizuno Wave Prophecy Ls Sport",
    category: "Mizuno Wave Prophecy",
    variant: "LS Sport",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-sport-102300003-3-560.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Sport. Versão esportiva da linha LS para performance e lifestyle. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-064",
    name: "Tênis Mizuno Wave Prophecy Ls Sport",
    category: "Mizuno Wave Prophecy",
    variant: "LS Sport",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-sport-102300003-3-566.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Sport. Versão esportiva da linha LS para performance e lifestyle. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-065",
    name: "Tênis Mizuno Wave Prophecy Ls Sport",
    category: "Mizuno Wave Prophecy",
    variant: "LS Sport",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-sport-102300003-3-913.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Sport. Versão esportiva da linha LS para performance e lifestyle. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-066",
    name: "Tênis Mizuno Wave Prophecy LS Vrunk",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-vrunk-102356003-004.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Vrunk. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-067",
    name: "Tênis Mizuno Wave Prophecy MOC GTX",
    category: "Mizuno Wave Prophecy",
    variant: "MOC",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-moc-gtx-102253003-3-566.jpg",
    description: `Sinta a proteção do Gore-Tex impermeável com o icônico solado Prophecy. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "MOC",
    colors: ["Variada"],
  },
  {
    id: "mzp-068",
    name: "Tênis Mizuno Wave Prophecy MOC Suede",
    category: "Mizuno Wave Prophecy",
    variant: "MOC",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-moc-suede-102302003-3-014.jpg",
    description: `Sinta o luxo do suede com a lendária sola de amortecimento Prophecy. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "MOC",
    colors: ["Variada"],
  },
  {
    id: "mzp-069",
    name: "Tênis Mizuno Wave Prophecy Morelia Neo",
    category: "Mizuno Wave Prophecy",
    variant: "Morelia",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-morelia-neo-102343003-029.jpg",
    description: `Tênis Mizuno Wave Prophecy Morelia Neo. Collaboration com a linha Morelia, unindo performance e legado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Morelia",
    colors: ["Variada"],
  },
  {
    id: "mzp-070",
    name: "Tênis Mizuno Wave Prophecy Morelia Neo",
    category: "Mizuno Wave Prophecy",
    variant: "Morelia",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-morelia-neo-102343003-030.jpg",
    description: `Tênis Mizuno Wave Prophecy Morelia Neo. Collaboration com a linha Morelia, unindo performance e legado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Morelia",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-071",
    name: "Tênis Mizuno Wave Prophecy Vainl Archive",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-vainl-archive-102224003-3-030.jpg",
    description: `Tênis Mizuno Wave Prophecy Vainl Archive. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-072",
    name: "Tênis Sportstyle Mizuno Wave Prophecy LS Maharishi",
    category: "Mizuno Wave Prophecy",
    variant: "Collab",
    price: 399.9,
    image: "/products/tenis-sportstyle-mizuno-wave-prophecy-ls-maharishi-102402003-030.jpg",
    description: `Tênis Sportstyle Mizuno Wave Prophecy LS Maharishi. Edição de colaboração exclusiva — peça de coleção limitada. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Collab",
    colors: ["Variada"],
  },
  {
    id: "mzp-073",
    name: "Tênis Unissex Mizuno Wave Prophecy 13",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-unissex-mizuno-wave-prophecy-13-102183001-3-800.jpg",
    description: `Tênis Unissex Mizuno Wave Prophecy 13. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-074",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-unissex-mizuno-wave-prophecy-ls-102034003-3-030.jpg",
    description: `Tênis Mizuno Wave Prophecy LS. Linha Lifestyle — conforto premium para uso urbano e casual. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-075",
    name: "Tênis Unissex Mizuno Wave Prophecy LS x Beautiful People",
    category: "Mizuno Wave Prophecy",
    variant: "Collab",
    price: 399.9,
    image: "/products/tenis-unissex-mizuno-wave-prophecy-ls-x-beautiful-people-102158003-3-345.jpg",
    description: `Conquiste o mais alto nível de suporte com a tecnologia de leque duplo. Aproveite frete grátis* e parcelas em 10x s/ juros. Peça o seu!`,
    badge: "Collab",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  }
];

/**
 * Monta a URL do WhatsApp com a mensagem pré-preenchida,
 * já incluindo o tamanho selecionado pelo cliente.
 */
export function buildWhatsappUrl(product: Product, size?: number): string {
  const sizeText = size ? ` — Tamanho: ${size}` : "";
  const msg = `Olá! Acessei o site da Russo Store e gostaria de comprar o produto: ${product.name} (R$ ${product.price.toFixed(2).replace(".", ",")}). Código: ${product.id}${sizeText}.`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`;
}

export function buildGenericWhatsappUrl(): string {
  const msg = `Olá! Acessei o site da Russo Store e gostaria de mais informações sobre a linha Mizuno Wave Prophecy disponível.`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`;
}
