// Catálogo Russo Store — Linha Mizuno Wave Prophecy COMPLETA (69 modelos)
// Todos os produtos R$ 399,90 | Tamanhos 37 ao 45
// Imagens baixadas do site oficial Mizuno (https://www.mizuno.com.br/linha-wave-prophecy)

export type Product = {
  id: string;
  name: string;
  /** Categoria principal (multi-categoria e-commerce) */
  category: string;
  /** Variante interna da categoria (usado para filtros) */
  variant: string;
  price: number;
  image: string;
  description: string;
  highlight?: string;
  badge?: string;
  colors?: string[];
  /** Tamanhos disponíveis (sobrescreve SIZES global se definido) */
  sizes?: (string | number)[];
};

export const WHATSAPP_NUMBER = "5516992800385";
export const STORE_NAME = "Russo Store";

// Tamanhos brasileiros disponíveis para todos os modelos (calçados)
export const SIZES = [37, 38, 39, 40, 41, 42, 43, 44, 45] as const;

// Tamanhos para camisetas/roupas (formato PP–GGG)
export const SHIRT_SIZES = ["PP", "P", "M", "G", "GG", "XGG", "XXGG"] as const;

// Filtros rápidos por variante
export const CATEGORIES = [
  {
    id: "Todos",
    name: "Todos",
    description: "Coleção completa (69 modelos)",
    icon: "Footprints",
  },
  {
    id: "M",
    name: "Prophecy M",
    description: "Modelo principal Infinity Wave",
    icon: "Zap",
  },
  {
    id: "LS",
    name: "Prophecy LS",
    description: "Lifestyle urbano e casual",
    icon: "Sparkles",
  },
  {
    id: "Beta",
    name: "Beta",
    description: "Linha Beta — design arrojado",
    icon: "Hexagon",
  },
  {
    id: "MOC",
    name: "MOC",
    description: "Moc-toe premium",
    icon: "Crown",
  },
  {
    id: "Prophecy 13",
    name: "Prophecy 13",
    description: "Geração 13 clássica",
    icon: "Star",
  },
  {
    id: "Prophecy 14",
    name: "Prophecy 14",
    description: "Geração 14 atualizada",
    icon: "TrendingUp",
  },
  {
    id: "Collab",
    name: "Collabs",
    description: "Edições de colaboração",
    icon: "Award",
  },
  {
    id: "GTX",
    name: "GTX",
    description: "Gore-Tex impermeável",
    icon: "Droplets",
  },
  // ============ NOVAS CATEGORIAS ============
  {
    id: "Camisetas de Time",
    name: "Camisas de Times",
    description: "35 times brasileiros — Série A e B",
    icon: "Shield",
  },
] as const;

/**
 * Macro-categorias para o menu multi-categoria e-commerce.
 * Agrupa as variantes internas em departamentos visíveis no header.
 */
export const DEPARTMENTS = [
  {
    id: "calcados",
    name: "Calçados",
    icon: "Footprints",
    categories: ["M", "LS", "Beta", "MOC", "Prophecy 13", "Prophecy 14", "Collab", "GTX"],
  },
  {
    id: "camisetas-time",
    name: "Camisas de Times",
    icon: "Shield",
    categories: ["Camisetas de Time"],
  },
] as const;

export const PRODUCTS: Product[] = [
  {
    id: "mzp-001",
    name: "Tênis Casual Mizuno Wave Prophecy 13.2",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-13-2-102393003-004.jpg",
    description: `Sinta o aprimoramento constante de um tênis autêntico e moderno. Na loja tem frete grátis* e até 10x s/ juros. Garanta seu Prophecy hoje!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-002",
    name: "Tênis Casual Mizuno Wave Prophecy 13.2",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-13-2-102393003-030.jpg",
    description: `Sinta o aprimoramento constante de um tênis autêntico e moderno. Na loja tem frete grátis* e até 10x s/ juros. Garanta seu Prophecy hoje!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-003",
    name: "Tênis Casual Mizuno Wave Prophecy 13.2",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-13-2-102397003-012.jpg",
    description: `Sinta o aprimoramento constante de um tênis autêntico e moderno. Na loja tem frete grátis* e até 10x s/ juros. Garanta seu Prophecy hoje!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-004",
    name: "Tênis Casual Mizuno Wave Prophecy 13.2",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-13-2-102397003-014.jpg",
    description: `Sinta o aprimoramento constante de um tênis autêntico e moderno. Na loja tem frete grátis* e até 10x s/ juros. Garanta seu Prophecy hoje!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-005",
    name: "Tênis Casual Mizuno Wave Prophecy Beta 2 Fashion Lover",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-beta-2-fashion-lover-102208003-3-204.jpg",
    description: `Adote o visual ousado e tecnológico da entressola Infinity Wave. Aproveite frete grátis* e até 10x s/ juros na loja. Garanta o seu par já!`,
    badge: "Beta",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-006",
    name: "Tênis Casual Mizuno Wave Prophecy LS Suede",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-ls-suede-unissex-cinza-8215.jpg",
    description: `Tênis Casual Mizuno Wave Prophecy LS Suede. Linha Lifestyle — conforto premium para uso urbano e casual. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Cinza"],
  },
  {
    id: "mzp-007",
    name: "Tênis Casual Mizuno Wave Prophecy LS Suede",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-casual-mizuno-wave-prophecy-ls-suede-unissex-marrom-8216.jpg",
    description: `Tênis Casual Mizuno Wave Prophecy LS Suede. Linha Lifestyle — conforto premium para uso urbano e casual. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Marrom"],
  },
  {
    id: "mzp-008",
    name: "Tênis Casual Unissex Mizuno Wave Prophecy Beta",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-casual-unissex-mizuno-wave-prophecy-beta-102015003-3-054.jpg",
    description: `Tênis Casual Unissex Mizuno Wave Prophecy Beta. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-009",
    name: "Tênis Feminino Mizuno Wave Prophecy 13",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-feminino-mizuno-wave-prophecy-13-102184002-2-262.jpg",
    description: `Tênis Feminino Mizuno Wave Prophecy 13. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-010",
    name: "Tênis Mizuno Wave Prophecy 13.2 Gradation",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-mizuno-prophecy-13-2-gradation-unissex-cinza-claro-11325.jpg",
    description: `Tênis Mizuno Wave Prophecy 13.2 Gradation. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    highlight: "Original Mizuno",
    colors: ["Cinza"],
  },
  {
    id: "mzp-011",
    name: "Tênis Mizuno Prophecy LS x Hiroshi Nagai",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-prophecy-ls-x-hiroshi-nagai-102197003-3-090.jpg",
    description: `Tênis Mizuno Prophecy LS x Hiroshi Nagai. Linha Lifestyle — conforto premium para uso urbano e casual. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-012",
    name: "Tênis Mizuno Wave Prophecy 13",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-13-102183001-3-036.jpg",
    description: `Corra com a estabilidade máxima da placa Infinity Wave. Na nossa loja tem frete grátis* e em 10x s/ juros. Garanta o seu lançamento já!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-013",
    name: "Tênis Mizuno Wave Prophecy 13.2 Vrunk",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-13-2-vrunk-102403003-030.jpg",
    description: `Vista a collab exclusiva Mizuno + VRUNK com estilo urbano único. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-014",
    name: "Tênis Mizuno Wave Prophecy 13-S",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-13-s-102185001-1-014.jpg",
    description: `Tênis Mizuno Wave Prophecy 13-S. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-015",
    name: "Tênis Mizuno Wave Prophecy 14",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-102289003-3-033.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Geração 14",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-016",
    name: "Tênis Mizuno Wave Prophecy 14",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-102289003-3-926.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-017",
    name: "Tênis Mizuno Wave Prophecy 14",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-102322003-3-053.jpg",
    description: `Tênis Mizuno Wave Prophecy 14. Geração 14 com atualizações de cabedal e entressola. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-018",
    name: "Tênis Mizuno Wave Prophecy 14-S",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-s-102290003-3-243.jpg",
    description: `Tênis Mizuno Wave Prophecy 14-S. Geração 14 com atualizações de cabedal e entressola. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 14",
    colors: ["Variada"],
  },
  {
    id: "mzp-019",
    name: "Tênis Mizuno Wave Prophecy 14-S",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-s-masculino-azul-8434.jpg",
    description: `Tênis Mizuno Wave Prophecy 14-S. Geração 14 com atualizações de cabedal e entressola. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 14",
    colors: ["Azul"],
  },
  {
    id: "mzp-020",
    name: "Tênis Mizuno Wave Prophecy 14-S",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 14",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-14-s-unissex-preto-8437.jpg",
    description: `Tênis Mizuno Wave Prophecy 14-S. Geração 14 com atualizações de cabedal e entressola. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 14",
    highlight: "Original Mizuno",
    colors: ["Preto"],
  },
  {
    id: "mzp-021",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102364003-012.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-022",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102364003-030.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-023",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102364003-033.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-024",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102365001-004.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-025",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102365001-012.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-026",
    name: "Tênis Mizuno Wave Prophecy 15",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-102365001-030.jpg",
    description: `Sinta o conforto da tecnologia Enerzy NXT e máxima estabilidade. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-027",
    name: "Tênis Mizuno Wave Prophecy 15 SE",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-se-102389003-012.jpg",
    description: `Sinta o conforto Enerzy NXT com caixa especial de 15 anos da linha. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-028",
    name: "Tênis Mizuno Wave Prophecy 15 SE",
    category: "Mizuno Wave Prophecy",
    variant: "M",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-15-se-102389003-030.jpg",
    description: `Sinta o conforto Enerzy NXT com caixa especial de 15 anos da linha. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-029",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-1-345.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-030",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-1-440.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-031",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-3-059.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-032",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-3-540.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-033",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-102116003-3-639.jpg",
    description: `Sinta o amortecimento com placa WAVE e cabedal leve nos treinos. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "Beta",
    colors: ["Variada"],
  },
  {
    id: "mzp-034",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-unissex-azul-6368.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Azul"],
  },
  {
    id: "mzp-035",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-unissex-cinza-7899.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    highlight: "Original Mizuno",
    colors: ["Cinza"],
  },
  {
    id: "mzp-036",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-unissex-cinza-7905.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Cinza"],
  },
  {
    id: "mzp-037",
    name: "Tênis Mizuno Wave Prophecy Beta 2",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-unissex-marrom-6994.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Marrom"],
  },
  {
    id: "mzp-038",
    name: "Tênis Mizuno Wave Prophecy Beta 2 x Graphpaper",
    category: "Mizuno Wave Prophecy",
    variant: "Beta",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-beta-2-x-graphpaper-unissex-azul-7440.jpg",
    description: `Tênis Mizuno Wave Prophecy Beta 2 x Graphpaper. Linha Beta com design arrojado e cabedal em mesh respirável premium. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Beta",
    colors: ["Azul"],
  },
  {
    id: "mzp-039",
    name: "Tênis Mizuno Wave Prophecy LS  x Randomevent",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls--x-randomevent-102072001-1-030.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-040",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-004.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-041",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-012.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-042",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-015.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-043",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-016.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-044",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-566.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-045",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-102034003-3-938.jpg",
    description: `Um único Flex Groove vertical em todo o antepé diminui a flexibilidade e aumenta a capacidade de resposta, aprimorando a sensação propulsiva da transição intermediária para a ponta do pé.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-046",
    name: "Tênis Mizuno Wave Prophecy Ls Graphpaper",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-graphpaper-102230003-3-058.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Graphpaper. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-047",
    name: "Tênis Mizuno Wave Prophecy Ls Graphpaper",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-graphpaper-102261003-3-014.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Graphpaper. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-048",
    name: "Tênis Mizuno Wave Prophecy LS GTX",
    category: "Mizuno Wave Prophecy",
    variant: "GTX",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-gtx-102342003-030.jpg",
    description: `Tênis Mizuno Wave Prophecy LS GTX. Tecnologia Gore-Tex impermeável para qualquer condição climática. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "GTX",
    colors: ["Variada"],
  },
  {
    id: "mzp-049",
    name: "Tênis Mizuno Wave Prophecy LS Midnight Velocity",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-midnight-velocity-102392003-004.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Midnight Velocity. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-050",
    name: "Tênis Mizuno Wave Prophecy LS Midnight Velocity",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-midnight-velocity-102392003-030.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Midnight Velocity. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-051",
    name: "Tênis Mizuno Wave Prophecy LS Millennium",
    category: "Mizuno Wave Prophecy",
    variant: "Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-millennium-102310003-3-030.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Millennium. Edição especial com acabamento premium e detalhes únicos. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Edição Especial",
    colors: ["Variada"],
  },
  {
    id: "mzp-052",
    name: "Tênis Mizuno Wave Prophecy LS Mimetics",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-mimetics-unissex-cinza-8188.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Mimetics. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Cinza"],
  },
  {
    id: "mzp-053",
    name: "Tênis Mizuno Wave Prophecy LS Neon",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-neon-unissex-marrom-11323.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Neon. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Marrom"],
  },
  {
    id: "mzp-054",
    name: "Tênis Mizuno Wave Prophecy LS Nomad",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-nomad-unissex-bege-6395.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Nomad. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Edição Especial",
    colors: ["Bege"],
  },
  {
    id: "mzp-055",
    name: "Tênis Mizuno Wave Prophecy Ls Shinzo",
    category: "Mizuno Wave Prophecy",
    variant: "Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-shinzo-102262003-3-941.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Shinzo. Edição especial com acabamento premium e detalhes únicos. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Edição Especial",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-056",
    name: "Tênis Mizuno Wave Prophecy Ls Sport",
    category: "Mizuno Wave Prophecy",
    variant: "LS Sport",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-sport-102300003-3-362.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Sport. Versão esportiva da linha LS para performance e lifestyle. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-057",
    name: "Tênis Mizuno Wave Prophecy Ls Sport",
    category: "Mizuno Wave Prophecy",
    variant: "LS Sport",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-sport-102300003-3-560.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Sport. Versão esportiva da linha LS para performance e lifestyle. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-058",
    name: "Tênis Mizuno Wave Prophecy Ls Sport",
    category: "Mizuno Wave Prophecy",
    variant: "LS Sport",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-sport-102300003-3-566.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Sport. Versão esportiva da linha LS para performance e lifestyle. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-059",
    name: "Tênis Mizuno Wave Prophecy Ls Sport",
    category: "Mizuno Wave Prophecy",
    variant: "LS Sport",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-sport-102300003-3-913.jpg",
    description: `Tênis Mizuno Wave Prophecy Ls Sport. Versão esportiva da linha LS para performance e lifestyle. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-060",
    name: "Tênis Mizuno Wave Prophecy LS Vrunk",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-ls-vrunk-102356003-004.jpg",
    description: `Tênis Mizuno Wave Prophecy LS Vrunk. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-061",
    name: "Tênis Mizuno Wave Prophecy MOC GTX",
    category: "Mizuno Wave Prophecy",
    variant: "MOC",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-moc-gtx-102253003-3-566.jpg",
    description: `Sinta a proteção do Gore-Tex impermeável com o icônico solado Prophecy. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "MOC",
    colors: ["Variada"],
  },
  {
    id: "mzp-062",
    name: "Tênis Mizuno Wave Prophecy MOC Suede",
    category: "Mizuno Wave Prophecy",
    variant: "MOC",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-moc-suede-102302003-3-014.jpg",
    description: `Sinta o luxo do suede com a lendária sola de amortecimento Prophecy. Na loja tem frete grátis* e até 10x s/ juros. Peça o seu e garanta já!`,
    badge: "MOC",
    colors: ["Variada"],
  },
  {
    id: "mzp-063",
    name: "Tênis Mizuno Wave Prophecy Morelia Neo",
    category: "Mizuno Wave Prophecy",
    variant: "Morelia",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-morelia-neo-102343003-029.jpg",
    description: `Tênis Mizuno Wave Prophecy Morelia Neo. Collaboration com a linha Morelia, unindo performance e legado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Morelia",
    colors: ["Variada"],
  },
  {
    id: "mzp-064",
    name: "Tênis Mizuno Wave Prophecy Morelia Neo",
    category: "Mizuno Wave Prophecy",
    variant: "Morelia",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-morelia-neo-102343003-030.jpg",
    description: `Tênis Mizuno Wave Prophecy Morelia Neo. Collaboration com a linha Morelia, unindo performance e legado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Morelia",
    colors: ["Variada"],
  },
  {
    id: "mzp-065",
    name: "Tênis Mizuno Wave Prophecy Vainl Archive",
    category: "Mizuno Wave Prophecy",
    variant: "LS Special",
    price: 399.9,
    image: "/products/tenis-mizuno-wave-prophecy-vainl-archive-102224003-3-030.jpg",
    description: `Tênis Mizuno Wave Prophecy Vainl Archive. Colorway especial da linha LS, design único e diferenciado. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    highlight: "Original Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-066",
    name: "Tênis Sportstyle Mizuno Wave Prophecy LS Maharishi",
    category: "Mizuno Wave Prophecy",
    variant: "Collab",
    price: 399.9,
    image: "/products/tenis-sportstyle-mizuno-wave-prophecy-ls-maharishi-102402003-030.jpg",
    description: `Tênis Sportstyle Mizuno Wave Prophecy LS Maharishi. Edição de colaboração exclusiva — peça de coleção limitada. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Collab",
    colors: ["Variada"],
  },
  {
    id: "mzp-067",
    name: "Tênis Unissex Mizuno Wave Prophecy 13",
    category: "Mizuno Wave Prophecy",
    variant: "Prophecy 13",
    price: 399.9,
    image: "/products/tenis-unissex-mizuno-wave-prophecy-13-102183001-3-800.jpg",
    description: `Tênis Unissex Mizuno Wave Prophecy 13. Geração 13 com tecnologia Infinity Wave de amortecimento. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Geração 13",
    colors: ["Variada"],
  },
  {
    id: "mzp-068",
    name: "Tênis Mizuno Wave Prophecy LS",
    category: "Mizuno Wave Prophecy",
    variant: "LS",
    price: 399.9,
    image: "/products/tenis-unissex-mizuno-wave-prophecy-ls-102034003-3-030.jpg",
    description: `Tênis Mizuno Wave Prophecy LS. Linha Lifestyle — conforto premium para uso urbano e casual. Disponível do tamanho 37 ao 45. Produto original Mizuno com nota fiscal.`,
    badge: "Mizuno",
    colors: ["Variada"],
  },
  {
    id: "mzp-069",
    name: "Tênis Unissex Mizuno Wave Prophecy LS x Beautiful People",
    category: "Mizuno Wave Prophecy",
    variant: "Collab",
    price: 399.9,
    image: "/products/tenis-unissex-mizuno-wave-prophecy-ls-x-beautiful-people-102158003-3-345.jpg",
    description: `Conquiste o mais alto nível de suporte com a tecnologia de leque duplo. Aproveite frete grátis* e parcelas em 10x s/ juros. Peça o seu!`,
    badge: "Collab",
    colors: ["Variada"],
  }
];

/**
 * Monta a URL do WhatsApp com a mensagem pré-preenchida,
 * já incluindo o tamanho selecionado pelo cliente.
 */
export function buildWhatsappUrl(product: Product, size?: string | number): string {
  const sizeText = size ? ` — Tamanho: ${size}` : "";
  const msg = `Olá! Acessei o site da Russo Store e gostaria de comprar o produto: ${product.name} (R$ ${product.price.toFixed(2).replace(".", ",")}). Código: ${product.id}${sizeText}.`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`;
}

export function buildGenericWhatsappUrl(): string {
  const msg = `Olá! Acessei o site da Russo Store e gostaria de mais informações sobre a linha Mizuno Wave Prophecy disponível.`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`;
}

// ============================================================
// CAMISETAS DE TIMES BRASILEIROS (35 clubes — preço único R$ 129,90)
// ============================================================
const TIMES_BRASILEIROS: Product[] = [
  {
    id: "cbr-001",
    name: "Camisa do Flamengo 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/flamengo.jpg",
    description: `Camisa oficial do Flamengo, modelo 2024. Tecido Dry-Plus respirável, gola careca, mangas raglan. Cores rubro-negras tradicionais. Produto original com etiquetas de procedência. Tamanhos PP ao XXGG disponíveis. Estampas aplicadas em alta resolução, sem desbotamento. Compra direta via WhatsApp com atendimento personalizado.`,
    badge: "Mais vendida",
    colors: ["Rubro-Negro"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-002",
    name: "Camisa do Palmeiras 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/palmeiras.jpg",
    description: `Camisa oficial do Palmeiras 2024. Verde clássico com detalhes brancos, gola careca, tecido respirável. Equipamento autêntico do Verdão, com estampas em alta definição. Disponível nos tamanhos PP ao XXGG. Original com selo de autenticidade. Garanta a sua e mostre o seu amor pelo Palestra.`,
    badge: "Mais vendida",
    colors: ["Verde"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-003",
    name: "Camisa do Corinthians 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/corinthians.jpg",
    description: `Camisa oficial do Corinthians 2024. Padrão alvinegro clássico, com listras horizontais icônicas. Gola careca, mangas raglan e tecido Dry-Plus. Produto original do Timão, com acabamento premium. Disponível do PP ao XXGG. Vista as cores do Corinthians em qualquer lugar.`,
    badge: "Mais vendida",
    colors: ["Alvinegro"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-004",
    name: "Camisa do São Paulo 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/sao-paulo.jpg",
    description: `Camisa oficial do São Paulo FC 2024. Tricolor paulista — vermelho, preto e branco — em design moderno. Gola careca, tecido Dry-Plus respirável. Produto original com etiquetas de procedência. Tamanhos PP ao XXGG disponíveis. Vista o manto do Tricolor Paulista com autenticidade e conforto.`,
    colors: ["Tricolor"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-005",
    name: "Camisa do Santos 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/santos.jpg",
    description: `Camisa oficial do Santos FC 2024. Branco imaculado com listras pretas na manga. Gola careca, tecido respirável Dry-Plus. Produto original do Peixe, com etiqueta de autenticidade. Tamanhos PP ao XXGG. Vista o manto da Baixada Santista com orgulho e estilo.`,
    colors: ["Branco"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-006",
    name: "Camisa do Atlético-MG 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/atletico-mg.jpg",
    description: `Camisa oficial do Atlético Mineiro 2024. Alvinegro mineiro com listras verticais. Gola careca, tecido Dry-Plus respirável. Produto original do Galo, com acabamento premium. Tamanhos PP ao XXGG disponíveis. Vista as cores do Clube Atlético Mineiro em qualquer ocasião.`,
    badge: "Mais vendida",
    colors: ["Alvinegro"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-007",
    name: "Camisa do Cruzeiro 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/cruzeiro.jpg",
    description: `Camisa oficial do Cruzeiro 2024. Azul cabul com detalhes brancos e detalhes em amarelo. Gola careca, tecido respirável Dry-Plus. Produto original do Cabuloso, com etiqueta de procedência. Tamanhos PP ao XXGG. Mostre a sua paixão pelo Cruzeiro Raposa.`,
    colors: ["Azul"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-008",
    name: "Camisa do Grêmio 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/gremio.jpg",
    description: `Camisa oficial do Grêmio 2024. Tricolor gaúcho — azul, preto e branco — em listras verticais. Gola careca, tecido respirável. Produto original do Tricolor dos Pampas. Tamanhos PP ao XXGG disponíveis. Vista o manto do Imortal Tricolor com orgulho.`,
    colors: ["Tricolor"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-009",
    name: "Camisa do Internacional 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/internacional.jpg",
    description: `Camisa oficial do Internacional 2024. Vermelho Colorado com listras brancas verticais. Gola careca, tecido Dry-Plus respirável. Produto original do Inter, com etiqueta de procedência. Tamanhos PP ao XXGG. Vista o manto do Colorado e mostre o seu amor pelo Clube do Povo.`,
    badge: "Mais vendida",
    colors: ["Vermelho"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-010",
    name: "Camisa do Fluminense 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/fluminense.jpg",
    description: `Camisa oficial do Fluminense 2024. Tricolor carioca — verde, grená e branco — em diagonal icônica. Gola careca, tecido respirável Dry-Plus. Produto original do Flu, com acabamento premium. Tamanhos PP ao XXGG disponíveis. Mostre a sua paixão pelo Tricolor das Laranjeiras.`,
    colors: ["Tricolor"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-011",
    name: "Camisa do Vasco da Gama 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/vasco.jpg",
    description: `Camisa oficial do Vasco da Gama 2024. Cruzmaltina clássica, com listras diagonais pretas e brancas. Gola careca, tecido Dry-Plus. Produto original do Vasco, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Cruzmaltino e mostre o seu orgulho Gigante.`,
    badge: "Mais vendida",
    colors: ["Cruzmaltino"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-012",
    name: "Camisa do Botafogo 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/botafogo.jpg",
    description: `Camisa oficial do Botafogo 2024. Alvinegra clássica com estrela solitária. Gola careca, tecido Dry-Plus respirável. Produto original do Fogão, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Glorioso e mostre o seu amor pelo Alvinegro Carioca.`,
    colors: ["Alvinegro"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-013",
    name: "Camisa do Athletico-PR 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/athletico-pr.jpg",
    description: `Camisa oficial do Athletico Paranaense 2024. Vermelho com listras pretas verticais. Gola careca, tecido Dry-Plus respirável. Produto original do Furacão, com acabamento premium. Tamanhos PP ao XXGG disponíveis. Mostre a sua paixão pelo Furacão do Paraná em qualquer ocasião.`,
    colors: ["Vermelho-Preto"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-014",
    name: "Camisa do Bahia 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/bahia.jpg",
    description: `Camisa oficial do Esporte Clube Bahia 2024. Azul royal com detalhes brancos e vermelhos. Gola careca, tecido respirável Dry-Plus. Produto original do Esquadrão de Aço, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Bahia com orgulho e autenticidade.`,
    colors: ["Azul-Branco"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-015",
    name: "Camisa do Fortaleza 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/fortaleza.jpg",
    description: `Camisa oficial do Fortaleza EC 2024. Azul royal com detalhes vermelhos e brancos. Gola careca, tecido Dry-Plus respirável. Produto original do Leão do Pici, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre a sua paixão pelo Leão do Ceará em qualquer ocasião.`,
    badge: "Mais vendida",
    colors: ["Azul-Vermelho"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-016",
    name: "Camisa do Ceará 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/ceara.jpg",
    description: `Camisa oficial do Ceará Sporting Club 2024. Alvinegra clássica com listras verticais. Gola careca, tecido respirável Dry-Plus. Produto original do Vozão, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Vozão do Ceará com orgulho em qualquer lugar.`,
    colors: ["Alvinegro"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-017",
    name: "Camisa do Sport Recife 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/sport.jpg",
    description: `Camisa oficial do Sport Club Recife 2024. Vermelho com detalhes pretos. Gola careca, tecido Dry-Plus respirável. Produto original do Leão da Ilha, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre o seu amor pelo Leão da Ilha em qualquer ocasião.`,
    colors: ["Vermelho-Preto"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-018",
    name: "Camisa do Vitória 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/vitoria.jpg",
    description: `Camisa oficial do Esporte Clube Vitória 2024. Rubro-negro baiano com listras verticais. Gola careca, tecido Dry-Plus respirável. Produto original do Leão da Barra, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Leão da Barra com orgulho e estilo.`,
    colors: ["Rubro-Negro"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-019",
    name: "Camisa da Chapecoense 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/chapecoense.jpg",
    description: `Camisa oficial da Chapecoense 2024. Verde com detalhes brancos. Gola careca, tecido Dry-Plus respirável. Produto original do Verdão do Oeste, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores da Chapecoense com orgulho e respeito eterno.`,
    colors: ["Verde"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-020",
    name: "Camisa do Goiás 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/goias.jpg",
    description: `Camisa oficial do Goiás Esporte Clube 2024. Verde esmeralda com detalhes brancos. Gola careca, tecido respirável Dry-Plus. Produto original do Esmeraldino, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre a sua paixão pelo Verdão do Cerrado.`,
    colors: ["Verde"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-021",
    name: "Camisa do Atlético-GO 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/atletico-go.jpg",
    description: `Camisa oficial do Atlético Goianiense 2024. Vermelho com detalhes pretos. Gola careca, tecido Dry-Plus respirável. Produto original do Dragão, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Dragão Goiano com orgulho e autenticidade.`,
    colors: ["Vermelho-Preto"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-022",
    name: "Camisa do Coritiba 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/coritiba.jpg",
    description: `Camisa oficial do Coritiba 2024. Verde e branco com listras verticais. Gola careca, tecido respirável Dry-Plus. Produto original do Coxa-Branca, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre o seu amor pelo Coxa com orgulho em qualquer ocasião.`,
    colors: ["Verde-Branco"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-023",
    name: "Camisa do Juventude 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/juventude.jpg",
    description: `Camisa oficial do Juventude 2024. Verde com detalhes brancos. Gola careca, tecido Dry-Plus respirável. Produto original do Jasy, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Jasy com orgulho e autenticidade em qualquer ambiente.`,
    colors: ["Verde"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-024",
    name: "Camisa do Cuiabá 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/cuiaba.jpg",
    description: `Camisa oficial do Cuiabá EC 2024. Amarelo dourado com detalhes verdes. Gola careca, tecido respirável Dry-Plus. Produto original do Dourado, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre a sua paixão pelo Dourado Mato-grossense com estilo.`,
    colors: ["Amarelo-Verde"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-025",
    name: "Camisa do Bragantino 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/bragantino.jpg",
    description: `Camisa oficial do Red Bull Bragantino 2024. Branco com detalhes vermelhos. Gola careca, tecido Dry-Plus respirável. Produto original do Massa Bruta, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Massa Bruta com orgulho e modernidade.`,
    colors: ["Branco-Vermelho"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-026",
    name: "Camisa do América-MG 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/america-mg.jpg",
    description: `Camisa oficial do América Mineiro 2024. Verde com detalhes brancos. Gola careca, tecido respirável Dry-Plus. Produto original do Coelho, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre o seu amor pelo Coelho em qualquer ocasião com autenticidade.`,
    colors: ["Verde-Branco"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-027",
    name: "Camisa do Náutico 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/nautico.jpg",
    description: `Camisa oficial do Náutico Capibaribe 2024. Vermelho e branco com listras verticais. Gola careca, tecido Dry-Plus respirável. Produto original do Timbu, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Timbu com orgulho e tradição pernambucana.`,
    colors: ["Vermelho-Branco"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-028",
    name: "Camisa da Ponte Preta 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/ponte-preta.jpg",
    description: `Camisa oficial da Ponte Preta 2024. Preto com detalhes brancos. Gola careca, tecido Dry-Plus respirável. Produto original da Macaca, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre a sua paixão pela Macaca Campineira com orgulho e tradição.`,
    colors: ["Alvinegro"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-029",
    name: "Camisa do Guarani 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/guarani.jpg",
    description: `Camisa oficial do Guarani FC 2024. Verde com detalhes brancos. Gola careca, tecido respirável Dry-Plus. Produto original do Bugre, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Bugre Campineiro com orgulho e história centenária.`,
    colors: ["Verde"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-030",
    name: "Camisa do Avaí 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/avai.jpg",
    description: `Camisa oficial do Avaí FC 2024. Azul com detalhes brancos. Gola careca, tecido Dry-Plus respirável. Produto original do Leão da Serra, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre o seu amor pelo Leão da Serra Catarinense em qualquer ambiente.`,
    colors: ["Azul-Branco"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-031",
    name: "Camisa do Criciúma 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/criciuma.jpg",
    description: `Camisa oficial do Criciúma EC 2024. Amarelo e preto com listras horizontais. Gola careca, tecido Dry-Plus respirável. Produto original do Tigre, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Tigro Catarinense com orgulho e tradição.`,
    colors: ["Amarelo-Preto"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-032",
    name: "Camisa do Vila Nova 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/vila-nova.jpg",
    description: `Camisa oficial do Vila Nova GO 2024. Vermelho com detalhes brancos. Gola careca, tecido Dry-Plus respirável. Produto original do Tigre Goiano, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre a sua paixão pelo Tigre Goiano com autenticidade e orgulho.`,
    colors: ["Vermelho-Branco"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-033",
    name: "Camisa do Operário-PR 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/operario-pr.jpg",
    description: `Camisa oficial do Operário Ferroviário 2024. Preto com detalhes brancos. Gola careca, tecido respirável Dry-Plus. Produto original do Fantasma da Sul, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Fantasma da Sul Matogrossense com orgulho e estilo.`,
    colors: ["Alvinegro"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-034",
    name: "Camisa do Londrina 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/londrina.jpg",
    description: `Camisa oficial do Londrina EC 2024. Azul com detalhes brancos. Gola careca, tecido Dry-Plus respirável. Produto original do Tubarão, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Mostre o seu amor pelo Tubarão do Norte Paranaense em qualquer ocasião.`,
    colors: ["Azul-Branco"],
    sizes: [...SHIRT_SIZES],
  },
  {
    id: "cbr-035",
    name: "Camisa do Figueirense 2024",
    category: "Camisetas de Time",
    variant: "Camisetas de Time",
    price: 129.9,
    image: "/products/camisas-times/figueirense.jpg",
    description: `Camisa oficial do Figueirense 2024. Preto e branco com listras. Gola careca, tecido Dry-Plus respirável. Produto original do Furacão do Estreito, com etiqueta de procedência. Tamanhos PP ao XXGG disponíveis. Vista as cores do Furacão do Estreito Catarinense com orgulho e tradição.`,
    colors: ["Alvinegro"],
    sizes: [...SHIRT_SIZES],
  },
];

// Concatena os times aos produtos existentes
export const TIMES_PRODUCTS = TIMES_BRASILEIROS;

// Lista final de produtos (Mizuno + Camisetas)
export const ALL_PRODUCTS: Product[] = [...PRODUCTS, ...TIMES_BRASILEIROS];
